<?php

namespace Ircbot\Module;

require_once dirname(__FILE__) . '/../../src/Module/AModule.php';

/**
 * Test class for AModule.
 * Generated by PHPUnit on 2012-02-11 at 23:52:03.
 */
class AModuleTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AModule
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AModule;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
