<?php

namespace Ircbot\Type;

require_once dirname(__FILE__) . '/../../src/Type/Bot.php';

/**
 * Test class for Bot.
 * Generated by PHPUnit on 2012-02-11 at 23:52:04.
 */
class BotTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Bot
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Bot;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Type\Bot::connect
     * @todo Implement testConnect().
     */
    public function testConnect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Bot::handleSocket
     * @todo Implement testHandleSocket().
     */
    public function testHandleSocket() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Bot::handleQueueOut
     * @todo Implement testHandleQueueOut().
     */
    public function testHandleQueueOut() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Bot::handleQueueIn
     * @todo Implement testHandleQueueIn().
     */
    public function testHandleQueueIn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Bot::handleQueueParsed
     * @todo Implement testHandleQueueParsed().
     */
    public function testHandleQueueParsed() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Bot::sendRawData
     * @todo Implement testSendRawData().
     */
    public function testSendRawData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Bot::privMsg
     * @todo Implement testPrivMsg().
     */
    public function testPrivMsg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Bot::msg
     * @todo Implement testMsg().
     */
    public function testMsg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Bot::notice
     * @todo Implement testNotice().
     */
    public function testNotice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Bot::join
     * @todo Implement testJoin().
     */
    public function testJoin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Bot::part
     * @todo Implement testPart().
     */
    public function testPart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Bot::disconnected
     * @todo Implement testDisconnected().
     */
    public function testDisconnected() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
