<?php

namespace Ircbot\Type;

require_once dirname(__FILE__) . '/../../src/Type/Channel.php';

/**
 * Test class for Channel.
 * Generated by PHPUnit on 2012-02-11 at 23:52:04.
 */
class ChannelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Channel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Channel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Type\Channel::isOp
     * @todo Implement testIsOp().
     */
    public function testIsOp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
