<?php

namespace Ircbot\Type;

require_once dirname(__FILE__) . '/../../src/Type/Mask.php';

/**
 * Test class for Mask.
 * Generated by PHPUnit on 2012-02-11 at 23:52:03.
 */
class MaskTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Mask
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Mask;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Type\Mask::fromMask
     * @todo Implement testFromMask().
     */
    public function testFromMask() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Mask::__toString
     * @todo Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
