<?php

namespace Ircbot\Type;

require_once dirname(__FILE__) . '/../../src/Type/Network.php';

/**
 * Test class for Network.
 * Generated by PHPUnit on 2012-02-11 at 23:52:06.
 */
class NetworkTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Network
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Network;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Type\Network::addISupport
     * @todo Implement testAddISupport().
     */
    public function testAddISupport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
