<?php

namespace Ircbot\Type;

require_once dirname(__FILE__) . '/../../src/Type/Queue.php';

/**
 * Test class for Queue.
 * Generated by PHPUnit on 2012-02-11 at 23:52:06.
 */
class QueueTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Queue
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Queue;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Type\Queue::getFirstEntry
     * @todo Implement testGetFirstEntry().
     */
    public function testGetFirstEntry() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Queue::delFirstEntry
     * @todo Implement testDelFirstEntry().
     */
    public function testDelFirstEntry() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Queue::shift
     * @todo Implement testShift().
     */
    public function testShift() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Queue::addEntry
     * @todo Implement testAddEntry().
     */
    public function testAddEntry() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Queue::addEntries
     * @todo Implement testAddEntries().
     */
    public function testAddEntries() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Queue::getEntryCount
     * @todo Implement testGetEntryCount().
     */
    public function testGetEntryCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Queue::clean
     * @todo Implement testClean().
     */
    public function testClean() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Type\Queue::isEmpty
     * @todo Implement testIsEmpty().
     */
    public function testIsEmpty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
