<?php

namespace Ircbot\Type;

require_once dirname(__FILE__) . '/../../src/Type/Response.php';

/**
 * Test class for Response.
 * Generated by PHPUnit on 2012-02-11 at 23:52:04.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Response;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
