<?php

namespace Ircbot\Type;

require_once dirname(__FILE__) . '/../../src/Type/Topic.php';

/**
 * Test class for Topic.
 * Generated by PHPUnit on 2012-02-11 at 23:52:04.
 */
class TopicTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Topic
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Topic;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
