<?php

require_once dirname(__FILE__) . '/../../src/Types/Topic.php';

/**
 * Test class for IRCBot_Types_Topic.
 * Generated by PHPUnit on 2011-12-06 at 21:35:59.
 */
class IRCBot_Types_TopicTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Types_Topic
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Types_Topic;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
