<?php

require_once dirname(__FILE__) . '/../../src/Types/Mask.php';

/**
 * Test class for IRCBot_Types_Mask.
 * Generated by PHPUnit on 2011-12-06 at 21:35:58.
 */
class IRCBot_Types_MaskTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Types_Mask
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Types_Mask;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testFromMask().
     */
    public function testFromMask() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
