<?php

require_once dirname(__FILE__) . '/../../src/Types/Mask.php';

/**
 * Test class for IRCBot_Types_Mask.
 * Generated by PHPUnit on 2011-12-06 at 21:35:58.
 */
class IRCBot_Types_MaskTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Types_Mask
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Types_Mask;
        $this->object->fromMask('nick!user@host');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function testFromMask() {
        $this->assertEquals('nick', $this->object->nickname);
        $this->assertEquals('user', $this->object->ident);
        $this->assertEquals('host', $this->object->host);
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function test__toString() {
        $this->assertEquals('nick!user@host', (string) $this->object);
    }

}

?>
