<?php

namespace Ircbot\Utility;

require_once dirname(__FILE__) . '/../../src/Utility/String.php';

/**
 * Test class for String.
 * Generated by PHPUnit on 2012-02-11 at 23:51:58.
 */
class StringTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var String
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new String;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Utility\String::tokenize
     * @todo Implement testTokenize().
     */
    public function testTokenize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Utility\String::token
     * @todo Implement testToken().
     */
    public function testToken() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Utility\String::tokenizeCleanup
     * @todo Implement testTokenizeCleanup().
     */
    public function testTokenizeCleanup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Utility\String::removeNewlines
     * @todo Implement testRemoveNewlines().
     */
    public function testRemoveNewlines() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
