<?php

namespace Ircbot;

require_once dirname(__FILE__) . '/../src/Application.php';

/**
 * Test class for Application.
 * Generated by PHPUnit on 2012-02-11 at 23:51:57.
 */
class ApplicationTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Application
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Application;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Application::getInstance
     * @todo Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::getEventHandler
     * @todo Implement testGetEventHandler().
     */
    public function testGetEventHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::getModuleHandler
     * @todo Implement testGetModuleHandler().
     */
    public function testGetModuleHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::getBotHandler
     * @todo Implement testGetBotHandler().
     */
    public function testGetBotHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::getSocketHandler
     * @todo Implement testGetSocketHandler().
     */
    public function testGetSocketHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::getQueueHandler
     * @todo Implement testGetQueueHandler().
     */
    public function testGetQueueHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::getCommandParser
     * @todo Implement testGetCommandParser().
     */
    public function testGetCommandParser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::getResponseHandler
     * @todo Implement testGetResponseHandler().
     */
    public function testGetResponseHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::getUserCommandHandler
     * @todo Implement testGetUserCommandHandler().
     */
    public function testGetUserCommandHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::getIdentifierHandler
     * @todo Implement testGetIdentifierHandler().
     */
    public function testGetIdentifierHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::getChannelHandler
     * @todo Implement testGetChannelHandler().
     */
    public function testGetChannelHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::getNetworkHandler
     * @todo Implement testGetNetworkHandler().
     */
    public function testGetNetworkHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::getLoop
     * @todo Implement testGetLoop().
     */
    public function testGetLoop() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::setDebugger
     * @todo Implement testSetDebugger().
     */
    public function testSetDebugger() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application::getDebugger
     * @todo Implement testGetDebugger().
     */
    public function testGetDebugger() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
