<?php

require_once dirname(__FILE__) . '/../src/Debugger.php';

/**
 * Test class for IRCBot_Debugger.
 * Generated by PHPUnit on 2011-12-06 at 21:35:56.
 */
class IRCBot_DebuggerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Debugger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Debugger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testLog().
     */
    public function testLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
