<?php

require_once dirname(__FILE__) . '/../src/Loop.php';

/**
 * Test class for IRCBot_Loop.
 * Generated by PHPUnit on 2011-12-06 at 21:35:55.
 */
class IRCBot_LoopTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Loop
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Loop;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function testStartLoop() {
        $this->assertEquals(10, $this->object->startLoop(10, function () {},
            function () {}));
        $this->assertEquals(25, $this->object->startLoop(25, function () {},
            function () {}));
        $this->assertEquals(100, $this->object->startLoop(100, function () {},
            function () {}));
        $this->assertEquals(250, $this->object->startLoop(250, function () {},
            function () {}));
    }

}

?>
