<?php

require_once dirname(__FILE__) . '/../../src/Utilities/String.php';

/**
 * Test class for IRCBot_Utilities_String.
 * Generated by PHPUnit on 2011-12-06 at 21:35:56.
 */
class IRCBot_Utilities_StringTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Utilities_String
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Utilities_String;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testTokenize().
     */
    public function testTokenize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testToken().
     */
    public function testToken() {
        // Remove the following lines when you implement this test.
        $testString = 'Hello! This sentence should be tokenized.';
        IRCBot_Utilities_String::tokenize($testString);
        
        $this->assertEquals('Hello!', IRCBot_Utilities_String::token('0'));
        
        /*$this->markTestIncomplete(
                'This test has not been implemented yet.'
        );*/
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testTokenizeCleanup().
     */
    public function testTokenizeCleanup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testRemoveNewlines().
     */
    public function testRemoveNewlines() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
