<?php

require_once dirname(__FILE__) . '/../../src/Handlers/Modules.php';

/**
 * Test class for IRCBot_Handlers_Modules.
 * Generated by PHPUnit on 2011-12-06 at 21:36:05.
 */
class IRCBot_Handlers_ModulesTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Handlers_Modules
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Handlers_Modules;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAddModuleByObject().
     */
    public function testAddModuleByObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetModuleByName().
     */
    public function testGetModuleByName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
