<?php

require_once dirname(__FILE__) . '/../../src/Handlers/Queues.php';

/**
 * Test class for IRCBot_Handlers_Queues.
 * Generated by PHPUnit on 2011-12-06 at 21:36:02.
 */
class IRCBot_Handlers_QueuesTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Handlers_Queues
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Handlers_Queues;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAddQueue().
     */
    public function testAddQueue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetQueueById().
     */
    public function testGetQueueById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
