<?php

require_once dirname(__FILE__) . '/../../src/Handlers/UserCommands.php';

/**
 * Test class for IRCBot_Handlers_UserCommands.
 * Generated by PHPUnit on 2011-12-06 at 21:36:03.
 */
class IRCBot_Handlers_UserCommandsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Handlers_UserCommands
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Handlers_UserCommands;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAddCommand().
     */
    public function testAddCommand() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testOnMsg().
     */
    public function testOnMsg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testSetDefaultMsgType().
     */
    public function testSetDefaultMsgType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testSetDefaultScanType().
     */
    public function testSetDefaultScanType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
