<?php

require_once dirname(__FILE__) . '/../../src/Handlers/Bots.php';

/**
 * Test class for IRCBot_Handlers_Bots.
 * Generated by PHPUnit on 2011-12-06 at 21:36:03.
 */
class IRCBot_Handlers_BotsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Handlers_Bots
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Handlers_Bots;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAddBot().
     */
    public function testAddBot() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testHandleBots().
     */
    public function testHandleBots() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetBotById().
     */
    public function testGetBotById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAllBotsExecute().
     */
    public function testAllBotsExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
