<?php

require_once dirname(__FILE__) . '/../../src/Handlers/Channels.php';

/**
 * Test class for IRCBot_Handlers_Channels.
 * Generated by PHPUnit on 2011-12-06 at 21:36:03.
 */
class IRCBot_Handlers_ChannelsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Handlers_Channels
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Handlers_Channels;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetChan().
     */
    public function testGetChan() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAddChan().
     */
    public function testAddChan() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testDelChan().
     */
    public function testDelChan() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
