<?php

require_once dirname(__FILE__) . '/../../src/Handlers/Networks.php';

/**
 * Test class for IRCBot_Handlers_Networks.
 * Generated by PHPUnit on 2011-12-06 at 21:36:02.
 */
class IRCBot_Handlers_NetworksTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Handlers_Networks
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Handlers_Networks;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
