<?php

namespace Ircbot\Application\Debug;

require_once dirname(__FILE__) . '/../../../src/Application/Debug/ADebug.php';

/**
 * Test class for ADebug.
 * Generated by PHPUnit on 2012-02-11 at 23:52:07.
 */
class ADebugTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ADebug
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ADebug;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
