<?php

namespace Ircbot\Handler;

require_once dirname(__FILE__) . '/../../src/Handler/Bots.php';

/**
 * Test class for Bots.
 * Generated by PHPUnit on 2012-02-11 at 23:51:59.
 */
class BotsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Bots
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Bots;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Handler\Bots::addBot
     * @todo Implement testAddBot().
     */
    public function testAddBot() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\Bots::handleBots
     * @todo Implement testHandleBots().
     */
    public function testHandleBots() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\Bots::getBotById
     * @todo Implement testGetBotById().
     */
    public function testGetBotById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\Bots::allBotsExecute
     * @todo Implement testAllBotsExecute().
     */
    public function testAllBotsExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
