<?php

namespace Ircbot\Handler;

require_once dirname(__FILE__) . '/../../src/Handler/Channels.php';

/**
 * Test class for Channels.
 * Generated by PHPUnit on 2012-02-11 at 23:52:01.
 */
class ChannelsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Channels
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Channels;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Handler\Channels::getChan
     * @todo Implement testGetChan().
     */
    public function testGetChan() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\Channels::addChan
     * @todo Implement testAddChan().
     */
    public function testAddChan() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\Channels::delChan
     * @todo Implement testDelChan().
     */
    public function testDelChan() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
