<?php

namespace Ircbot\Handler;

require_once dirname(__FILE__) . '/../../src/Handler/Events.php';

/**
 * Test class for Events.
 * Generated by PHPUnit on 2012-02-11 at 23:51:59.
 */
class EventsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Events
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Events;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Handler\Events::raiseEvent
     * @todo Implement testRaiseEvent().
     */
    public function testRaiseEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\Events::addEventCallback
     * @todo Implement testAddEventCallback().
     */
    public function testAddEventCallback() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
