<?php

namespace Ircbot\Handler;

require_once dirname(__FILE__) . '/../../src/Handler/Module.php';

/**
 * Test class for Module.
 * Generated by PHPUnit on 2012-02-11 at 23:51:59.
 */
class ModuleTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Module
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Module;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Handler\Module::addModuleByObject
     * @todo Implement testAddModuleByObject().
     */
    public function testAddModuleByObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\Module::getModuleByName
     * @todo Implement testGetModuleByName().
     */
    public function testGetModuleByName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
