<?php

namespace Ircbot\Handler;

require_once dirname(__FILE__) . '/../../src/Handler/Networks.php';

/**
 * Test class for Networks.
 * Generated by PHPUnit on 2012-02-11 at 23:51:58.
 */
class NetworksTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Networks
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Networks;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
