<?php

namespace Ircbot\Handler;

require_once dirname(__FILE__) . '/../../src/Handler/Queues.php';

/**
 * Test class for Queues.
 * Generated by PHPUnit on 2012-02-11 at 23:52:00.
 */
class QueuesTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Queues
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Queues;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Handler\Queues::addQueue
     * @todo Implement testAddQueue().
     */
    public function testAddQueue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\Queues::getQueueById
     * @todo Implement testGetQueueById().
     */
    public function testGetQueueById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
