<?php

namespace Ircbot\Handler;

require_once dirname(__FILE__) . '/../../src/Handler/Responses.php';

/**
 * Test class for Responses.
 * Generated by PHPUnit on 2012-02-11 at 23:51:59.
 */
class ResponsesTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Responses
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Responses;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Handler\Responses::handleResponse
     * @todo Implement testHandleResponse().
     */
    public function testHandleResponse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\Responses::handleCommand
     * @todo Implement testHandleCommand().
     */
    public function testHandleCommand() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\Responses::handleNumeric
     * @todo Implement testHandleNumeric().
     */
    public function testHandleNumeric() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
