<?php

namespace Ircbot\Handler;

require_once dirname(__FILE__) . '/../../src/Handler/Signals.php';

/**
 * Test class for Signals.
 * Generated by PHPUnit on 2012-02-11 at 23:52:01.
 */
class SignalsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Signals
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Signals;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Handler\Signals::getSignals
     * @todo Implement testGetSignals().
     */
    public function testGetSignals() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\Signals::handleSignal
     * @todo Implement testHandleSignal().
     */
    public function testHandleSignal() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
