<?php

namespace Ircbot\Handler;

require_once dirname(__FILE__) . '/../../src/Handler/Sockets.php';

/**
 * Test class for Sockets.
 * Generated by PHPUnit on 2012-02-11 at 23:52:01.
 */
class SocketsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Sockets
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Sockets;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Handler\Sockets::addSocket
     * @todo Implement testAddSocket().
     */
    public function testAddSocket() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\Sockets::getSocketById
     * @todo Implement testGetSocketById().
     */
    public function testGetSocketById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
