<?php

namespace Ircbot\Handler;

require_once dirname(__FILE__) . '/../../src/Handler/UserCommands.php';

/**
 * Test class for UserCommands.
 * Generated by PHPUnit on 2012-02-11 at 23:51:59.
 */
class UserCommandsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var UserCommands
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UserCommands;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Handler\UserCommands::addCommand
     * @todo Implement testAddCommand().
     */
    public function testAddCommand() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\UserCommands::onMsg
     * @todo Implement testOnMsg().
     */
    public function testOnMsg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\UserCommands::setDefaultMsgType
     * @todo Implement testSetDefaultMsgType().
     */
    public function testSetDefaultMsgType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Handler\UserCommands::setDefaultScanType
     * @todo Implement testSetDefaultScanType().
     */
    public function testSetDefaultScanType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
