<?php

namespace Ircbot\Application;

require_once dirname(__FILE__) . '/../../src/Application/Autoloader.php';

/**
 * Test class for Autoloader.
 * Generated by PHPUnit on 2012-02-11 at 23:51:58.
 */
class AutoloaderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Autoloader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Autoloader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Application\Autoloader::autoload
     * @todo Implement testAutoload().
     */
    public function testAutoload() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
