<?php

namespace Ircbot\Application;

require_once dirname(__FILE__) . '/../../src/Application/Loop.php';

/**
 * Test class for Loop.
 * Generated by PHPUnit on 2012-02-11 at 23:51:58.
 */
class LoopTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Loop
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Loop;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Application\Loop::startLoop
     * @todo Implement testStartLoop().
     */
    public function testStartLoop() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application\Loop::onStart
     * @todo Implement testOnStart().
     */
    public function testOnStart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ircbot\Application\Loop::onIterate
     * @todo Implement testOnIterate().
     */
    public function testOnIterate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
