<?php

require_once dirname(__FILE__) . '/../../src/Parsers/NameReply.php';

/**
 * Test class for IRCBot_Parsers_NameReply.
 * Generated by PHPUnit on 2011-12-06 at 21:35:59.
 */
class IRCBot_Parsers_NameReplyTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Parsers_NameReply
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Parsers_NameReply;
        if (!defined('CHAN_MODE_VOICE')) {
            define('CHAN_MODE_VOICE',  1);
        }
        if (!defined('CHAN_MODE_HALFOP')) {
            define('CHAN_MODE_HALFOP',  2);
        }
        if (!defined('CHAN_MODE_OP')) {
            define('CHAN_MODE_OP',  4);
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function testParseNames() {
        $start = ':server 353 bot = #channel :';
        $tests = array();
        $tests['@TestBot'] = array('TestBot' => CHAN_MODE_OP);
        $tests['+TestBot'] = array('TestBot' => CHAN_MODE_VOICE);
        $tests['+TestBot @TestUser'] = array('TestBot'  => CHAN_MODE_VOICE,
                                             'TestUser' => CHAN_MODE_OP);
        foreach ($tests as $data => $userlist) {
            $this->assertEquals($userlist, $this->object->parseNames($start . $data));
        }
    }

}

?>
