<?php

require_once dirname(__FILE__) . '/../../src/Parsers/NameReply.php';

/**
 * Test class for IRCBot_Parsers_NameReply.
 * Generated by PHPUnit on 2011-12-06 at 21:35:59.
 */
class IRCBot_Parsers_NameReplyTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Parsers_NameReply
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Parsers_NameReply;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testParseNames().
     */
    public function testParseNames() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
