<?php

require_once dirname(__FILE__) . '/../../src/Parsers/Commands.php';

/**
 * Test class for IRCBot_Parsers_Commands.
 * Generated by PHPUnit on 2011-12-06 at 21:35:59.
 */
class IRCBot_Parsers_CommandsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Parsers_Commands
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Parsers_Commands;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function testParseCommand() {
        $tests = array();
        $tests[':nick!user@host NOTICE BotName :Hey!'] = 'IRCBot_Commands_Notice';
        $tests['PING :TestPing'] = 'IRCBot_Commands_Ping';
        $tests['PONG :TestPong'] = 'IRCBot_Commands_Pong';
        $tests[':nick!user@host QUIT :TestPong'] = 'IRCBot_Commands_Quit';
        foreach ($tests as $text => $class) {
            $this->assertInstanceOf($class, $this->object->parseCommand($text));
        }
    }

}

?>
