<?php

require_once dirname(__FILE__) . '/../../src/Commands/Part.php';

/**
 * Test class for IRCBot_Commands_Part.
 * Generated by PHPUnit on 2012-01-14 at 20:47:05.
 */
class IRCBot_Commands_PartTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IRCBot_Commands_Part
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IRCBot_Commands_Part;
        $this->object->channel = '#channel';
        $this->object->mask = new IRCBot_Types_Mask;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testFromRawData().
     */
    public function testFromRawData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetEventName().
     */
    public function testGetEventName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetIdentifiers().
     */
    public function testGetIdentifiers() {
        $identifiers = $this->object->getIdentifiers();
        $this->assertArrayHasKey('chan', $identifiers);
        $this->assertArrayHasKey('nick', $identifiers);
        $this->assertEquals('#channel', $identifiers['chan']);
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
