<?php

namespace Ircbot\Parser;

require_once dirname(__FILE__) . '/../../src/Parser/Commands.php';

/**
 * Test class for Commands.
 * Generated by PHPUnit on 2012-02-11 at 23:52:06.
 */
class CommandsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Commands
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Commands;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Parser\Commands::parseCommand
     * @todo Implement testParseCommand().
     */
    public function testParseCommand() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
