<?php

namespace Ircbot\Parser;

require_once dirname(__FILE__) . '/../../src/Parser/NameReply.php';

/**
 * Test class for NameReply.
 * Generated by PHPUnit on 2012-02-11 at 23:52:06.
 */
class NameReplyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var NameReply
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new NameReply;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ircbot\Parser\NameReply::parseNames
     * @todo Implement testParseNames().
     */
    public function testParseNames() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
